INSERT INTO categories (id, name, slug)
VALUES (1, 'Электроника', 'electronika'),
       (2, 'Дом и сад', 'dom-i-sad'),
       (3, 'Детские товары', 'detskie-tovary'),
       (4, 'Аптека', 'apteka'),
       (5, 'Бытовая техника', 'bytovaya-tehnika'),
       (6, 'Книги', 'knigi'),
       (7, 'Строительство и ремонт', 'stroitelstvo-i-remont'),
       (8, 'Красота и здоровье', 'krasota-i-zdorove'),
       (9, 'Спортивные товары', 'sportivnye-tovary'),
       (10, 'Товары для животных', 'tovary-dlya-zhivotnyh'),
       (11, 'Автотовары', 'avtotovary'),
       (12, 'Товары для взрослых', 'tovary-dlya-vzroslyh'),
       (13, 'Туризм, рыбалка, охота', 'turizm-rybalka-ohota'),
       (14, 'Мебель', 'mebel'),
       (15, 'Цифровые товары', 'cifrovye-tovary'),
       (16, 'Антиквариат и коллекционирование', 'antikvariat-i-kollekcionirovanie'),
       (17, 'Канцелярские товары', 'kancelyarskie-tovary'),
       (18, 'Хобби и творчество', 'hobbi-i-tvorchestvo');
