"""add subcategory model

Revision ID: ed26ee26ce7b
Revises: 84c80f7cdfd7
Create Date: 2023-07-15 02:30:36.649399

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ed26ee26ce7b'
down_revision = '84c80f7cdfd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subcategories = op.create_table(
        'subcategories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'], ['categories.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.bulk_insert(
        subcategories,
        [
            # Электроника
            {'name': 'Смартфоны', 'category_id': 1},
            {'name': 'Планшеты', 'category_id': 1},
            {'name': 'Ноутбуки', 'category_id': 1},
            {'name': 'Телевизоры', 'category_id': 1},
            {'name': 'Компьютеры', 'category_id': 1},
            {'name': 'Смарт часы и фитнес-браслеты', 'category_id': 1},
            {'name': 'Аксессуары для смартфонов', 'category_id': 1},
            {'name': 'Наушники и аудиотехника', 'category_id': 1},
            {'name': 'Фото и видеокамеры', 'category_id': 1},
            {'name': 'Игры и консоли', 'category_id': 1},
            {'name': 'Умный дом и безопасность', 'category_id': 1},
            {'name': 'Офисная техника', 'category_id': 1},

            # Дом и сад
            {'name': 'Посуда', 'category_id': 2},
            {'name': 'Текстиль', 'category_id': 2},
            {'name': 'Декор и интерьер', 'category_id': 2},
            {'name': 'Хозяйственные товары', 'category_id': 2},
            {'name': 'Хранение вещей', 'category_id': 2},
            {'name': 'Аксессуары для ванной', 'category_id': 2},
            {'name': 'Дача и сад', 'category_id': 2},
            {'name': 'Цветы и растения', 'category_id': 2},
            {'name': 'Товары для праздника', 'category_id': 2},
            {'name': 'Освещение', 'category_id': 2},
            {'name': 'Религия и эстетика', 'category_id': 2},

            # Детские товары
            {'name': 'Игрушки и игры', 'category_id': 3},
            {'name': 'Спорт и игры на улице', 'category_id': 3},
            {'name': 'Детское творчество', 'category_id': 3},
            {'name': 'Настольные игры', 'category_id': 3},
            {'name': 'Для школы и обучения', 'category_id': 3},
            {'name': 'Подгузники и гигиена', 'category_id': 3},
            {'name': 'Коляски и автокресла', 'category_id': 3},
            {'name': 'Детская комната', 'category_id': 3},
            {'name': 'Товары для мам', 'category_id': 3},
            {'name': 'Товары для кормления', 'category_id': 3},

            # Аптека
            {'name': 'Лекарственные средства', 'category_id': 4},
            {'name': 'Мед. техника', 'category_id': 4},
            {'name': 'Спортпит', 'category_id': 4},
            {'name': 'Средства реабилитации', 'category_id': 4},
            {'name': 'Оптика', 'category_id': 4},
            {'name': 'Витамины', 'category_id': 4},

            # Бытовая техника
            {'name': 'Стиральные машины', 'category_id': 5},
            {'name': 'Холодильники', 'category_id': 5},
            {'name': 'Плиты', 'category_id': 5},
            {'name': 'Посудомоечные машины', 'category_id': 5},
            {'name': 'Пылесосы', 'category_id': 5},
            {'name': 'Кондиционеры и сплит системы', 'category_id': 5},

            # Книги
            {'name': 'Цифровые книги', 'category_id': 6},
            {'name': 'Художественная литература', 'category_id': 6},
            {'name': 'Детям и родителям', 'category_id': 6},
            {'name': 'Научная литература', 'category_id': 6},
            {'name': 'Саморазвитие', 'category_id': 6},
            {'name': 'Учебная литература', 'category_id': 6},

            # Строительство и ремонт
            {'name': 'Сантехника', 'category_id': 7},
            {'name': 'Инструменты', 'category_id': 7},
            {'name': 'Водоснабжение', 'category_id': 7},
            {'name': 'Отделочные материалы', 'category_id': 7},
            {'name': 'Строительные материалы', 'category_id': 7},
            {'name': 'Краски', 'category_id': 7},
            {'name': 'Электрика', 'category_id': 7},
            {'name': 'Двери и окна', 'category_id': 7},
            {'name': 'Дача и Сад', 'category_id': 7},
            {'name': 'Освещение', 'category_id': 7},
            {'name': 'Крепёж и фурнитура', 'category_id': 7},
            {'name': 'Отопление', 'category_id': 7},

            # Красота и здоровье
            {'name': 'Уход за лицом', 'category_id': 8},
            {'name': 'Уход за телом', 'category_id': 8},
            {'name': 'Уход за волосами', 'category_id': 8},
            {'name': 'Декоративная косметика', 'category_id': 8},
            {'name': 'Парфюмерия', 'category_id': 8},

            # Спортивные товары
            {'name': 'Велоспорт', 'category_id': 9},
            {'name': 'Электротранспорт', 'category_id': 9},
            {'name': 'Самокаты и аксессуары', 'category_id': 9},
            {'name': 'Фитнес и йога', 'category_id': 9},
            {'name': 'Виды спорта', 'category_id': 9},
            {'name': 'Спорт и отдых на воде', 'category_id': 9},
            {'name': 'Активный отдых', 'category_id': 9},
            {'name': 'Теннис и бадминтон', 'category_id': 9},
            {'name': 'Защита и экипировка', 'category_id': 9},
            {'name': 'Свободные веса', 'category_id': 9},
            {'name': 'Тренажеры', 'category_id': 9},
            {'name': 'Бокс и единоборства', 'category_id': 9},

            # Товары для животных
            {'name': 'Корм и лакомства', 'category_id': 10},
            {'name': 'Туалеты и наполнители', 'category_id': 10},
            {'name': 'Игрушки', 'category_id': 10},
            {'name': 'Амуниция', 'category_id': 10},
            {'name': 'Лежанки и миски', 'category_id': 10},
            {'name': 'Уход и груминг', 'category_id': 10},

            # Автотовары
            {'name': 'Масла и автохимия', 'category_id': 11},
            {'name': 'Автоаксессуары', 'category_id': 11},
            {'name': 'Шины и диски', 'category_id': 11},
            {'name': 'Автозапчасти', 'category_id': 11},
            {'name': 'Автозвук', 'category_id': 11},
            {'name': 'Уход за авто', 'category_id': 11},
            {'name': 'Автоинструменты', 'category_id': 11},
            {'name': 'Электроника для авто', 'category_id': 11},
            {'name': 'Гараж и автосервис', 'category_id': 11},
            {'name': 'Аккумуляторы', 'category_id': 11},
            {'name': 'Товары для мототехники', 'category_id': 11},
            {'name': 'Запчасти для спецтехники', 'category_id': 11},
            {'name': 'Запчасти для спецтехники', 'category_id': 11},

            # Товары для взрослых
            {'name': 'Секс игрушки', 'category_id': 12},
            {'name': 'Товары БДСВ', 'category_id': 12},
            {'name': 'Эротическое белье и костюмы', 'category_id': 12},
            {'name': 'Презервативы и лубриканты', 'category_id': 12},
            {'name': 'Интимная косметика', 'category_id': 12},
            {'name': 'Эротические сувениры и игры', 'category_id': 12},

            # Туризм, рыбалка, охота
            {'name': 'Туризм и отдых на природе', 'category_id': 13},
            {'name': 'Рыбалка', 'category_id': 13},
            {'name': 'Охота и стрельба', 'category_id': 13},
            {'name': 'Одежда для охоты и рыбалки', 'category_id': 13},
            {'name': 'Лодки и лодочные моторы', 'category_id': 13},
            {'name': 'Палатки, тенты и шатры', 'category_id': 13},
            {'name': 'Складная мебель', 'category_id': 13},
            {'name': 'Фонари и аксессуары', 'category_id': 13},
            {'name': 'Ножи, лопаты, пилы', 'category_id': 13},
            {'name': 'Горелки, походные печи', 'category_id': 13},
            {'name': 'Тактическая одежда', 'category_id': 13},
            {'name': 'Коврики туристические', 'category_id': 13},

            # Мебель
            {'name': 'Мягкая мебель', 'category_id': 14},
            {'name': 'Компьютерная мебель', 'category_id': 14},
            {'name': 'Бескаркасная мебель', 'category_id': 14},
            {'name': 'Столы и стулья', 'category_id': 14},
            {'name': 'Мебель для хранения', 'category_id': 14},
            {'name': 'Мебель для спальни', 'category_id': 14},
            {'name': 'Мебель для кухни', 'category_id': 14},
            {'name': 'Мебель для ванной', 'category_id': 14},
            {'name': 'Садовая мебель', 'category_id': 14},
            {'name': 'Детская мебель', 'category_id': 14},
            {'name': 'Мебель для бизнеса', 'category_id': 14},
            {'name': 'Сейфы и архивные шкафы', 'category_id': 14},

            # Цифровые товары
            {'name': 'Игры и игровые подписки', 'category_id': 15},
            {'name': 'Программное обеспечение', 'category_id': 15},
            {'name': 'Фильмы, музыка, и книги', 'category_id': 15},
            {'name': 'Облачные хранилища', 'category_id': 15},
            {'name': 'Другие подписки', 'category_id': 15},
            {'name': 'Подарочные сертификаты Ozon', 'category_id': 15},

            # Антиквариат и коллекционирование
            {'name': 'Коллекционирование', 'category_id': 16},
            {'name': 'Антикварная посуда', 'category_id': 16},
            {'name': 'Предмет интерьера', 'category_id': 16},
            {'name': 'Военная атрибутика', 'category_id': 16},
            {'name': 'Галантерея', 'category_id': 16},
            {'name': 'Антикварные книги', 'category_id': 16},

            # Канцелярские товары
            {'name': 'Рюкзаки, ранцы, сумки', 'category_id': 17},
            {'name': 'Тетради, дневники, блокноты', 'category_id': 17},
            {'name': 'Письменные принадлежности', 'category_id': 17},
            {'name': 'Канцелярские принадлежности', 'category_id': 17},
            {'name': 'Творчество в школе', 'category_id': 17},
            {'name': 'Рабочее место', 'category_id': 17},

            # Хобби и творчество
            {'name': 'Настольные игры', 'category_id': 18},
            {'name': 'Картины по номерам', 'category_id': 18},
            {'name': 'Алмазная мозаика', 'category_id': 18},
            {'name': 'Пазлы', 'category_id': 18},
            {'name': 'Наборы для опытов', 'category_id': 18},
            {'name': 'Бисер', 'category_id': 18},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategories')
    # ### end Alembic commands ###
