"""add category model

Revision ID: 84c80f7cdfd7
Revises: ac335de4a67e
Create Date: 2023-07-04 11:17:56.262313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '84c80f7cdfd7'
down_revision = 'ac335de4a67e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories = op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.bulk_insert(
        categories,
        [
            {'name': 'Электроника'},
            {'name': 'Дом и сад'},
            {'name': 'Детские товары'},
            {'name': 'Одежда, обувь и аксессуары'},
            {'name': 'Аптека'},
            {'name': 'Бытовая техника'},
            {'name': 'Книги'},
            {'name': 'Строительство и ремонт'},
            {'name': 'Красота и здоровье'},
            {'name': 'Товары для животных'},
            {'name': 'Продукты питания'},
            {'name': 'Автотовары'},
            {'name': 'Товары для взрослых'},
            {'name': 'Туризм, рыбалка, охота'},
            {'name': 'Все для игр'},
            {'name': 'Мебель'},
            {'name': 'Бытовая химия'},
            {'name': 'Ювелирные украшения'},
            {'name': 'Цифровые товары'},
            {'name': 'Антиквариат и коллекционирование'},
            {'name': 'Канцелярские товары'},
            {'name': 'Хобби и творчество'},
            {'name': 'Музыка и видео'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
