"""add category model

Revision ID: 84c80f7cdfd7
Revises: ac335de4a67e
Create Date: 2023-07-04 11:17:56.262313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '84c80f7cdfd7'
down_revision = 'ac335de4a67e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories = op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # ### end Alembic commands ###
    op.bulk_insert(
        categories,
        [
            {'id': 1, 'name': 'Электроника'},
            {'id': 2, 'name': 'Дом и сад'},
            {'id': 3, 'name': 'Детские товары'},
            {'id': 4, 'name': 'Аптека'},
            {'id': 5, 'name': 'Бытовая техника'},
            {'id': 6, 'name': 'Книги'},
            {'id': 7, 'name': 'Строительство и ремонт'},
            {'id': 8, 'name': 'Красота и здоровье'},
            {'id': 9, 'name': 'Спортивные товары'},
            {'id': 10, 'name': 'Товары для животных'},
            {'id': 11, 'name': 'Автотовары'},
            {'id': 12, 'name': 'Товары для взрослых'},
            {'id': 13, 'name': 'Туризм, рыбалка, охота'},
            {'id': 14, 'name': 'Мебель'},
            {'id': 15, 'name': 'Цифровые товары'},
            {'id': 16, 'name': 'Антиквариат и коллекционирование'},
            {'id': 17, 'name': 'Канцелярские товары'},
            {'id': 18, 'name': 'Хобби и творчество'},
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
